[package]
name = "river-swww"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3"
async-process = "2.3"
crossbeam-channel = "0.5"
dirs-next = "2.0"
futures-lite = "2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smol = "2.0"
smol-macros = "0.1"
